### ISSUE TITLE
深有同感

### ISSUE THREAD

**Issue by saicoco** [Yuanhang8605/pixel-anchor-link-and-text-detector-experience#1]
丢弃回归只用分割+link的方法idea确实漂亮，落地简直难受。实际中还是回归的方法好用，边界准确整齐。基于先验的anchor方法，根本不知道会遇到哪种文本跳出anchor范围

**Comment by Yuanhang8605** [comment]
@saicoco 实际上anchor是需要精细设计定制化的，anchor方法在复杂背景下更鲁棒，比较适合过拟合特定场景的文本检测需求

**Comment by saicoco** [comment]
确实，电商场景中的竖排，水平文本，anchor还是很有优势，不过在定制化场景，anchor可以用很简单的网络达到很好的效果

**Comment by wanghaisheng** [comment]
来吧 ocr讨论组的筒靴们等着大拿入群交流呢 
edwin_whs
