### ISSUE TITLE
请问你们的代码会考虑开源吗

### ISSUE THREAD

**Issue by lugeluge** [Yuanhang8605/pixel-anchor-link-and-text-detector-experience#8]
请问你们的代码会考虑开源吗，谢谢

**Comment by Yuanhang8605** [comment]
@lugeluge star太少，然后代码写得比较烂，maybe，后续有空了整理一下

**Comment by lugeluge** [comment]
@Yuanhang8605 因为我毕设有做的是ocr相关的，但是目前用的CTPN效果并不很满意。如果您打算开源的话非常感谢啦。会持续关注的
